# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: "3.7"

volumes:
  orderer.adey-meselesh.de:
  peer0.orgexporter.adey-meselesh.de:
  peer0.orgyccu.adey-meselesh.de:
  peer0.orgethiocta.adey-meselesh.de:
  peer0.orgsupplier.adey-meselesh.de:

networks:
  test:
    name: fabric_test

services:
  orderer.adey-meselesh.de:
    container_name: orderer.adey-meselesh.de
    image: hyperledger/fabric-orderer:latest
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=4000
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_BOOTSTRAPMETHOD=none
      - ORDERER_CHANNELPARTICIPATION_ENABLED=true
      - ORDERER_ADMIN_TLS_ENABLED=true
      - ORDERER_ADMIN_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_ADMIN_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_ADMIN_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_ADMIN_TLS_CLIENTROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_ADMIN_LISTENADDRESS=0.0.0.0:4001
      - ORDERER_OPERATIONS_LISTENADDRESS=orderer.adey-meselesh.de:4002
      - ORDERER_METRICS_PROVIDER=prometheus
    working_dir: /root
    command: orderer
    volumes:
      - ../organizations/ordererOrganizations/adey-meselesh.de/orderers/orderer.adey-meselesh.de/msp:/var/hyperledger/orderer/msp
      - ../organizations/ordererOrganizations/adey-meselesh.de/orderers/orderer.adey-meselesh.de/tls/:/var/hyperledger/orderer/tls
      - orderer.adey-meselesh.de:/var/hyperledger/production/orderer
    ports:
      - 4000:4000
      - 4001:4001
      - 4002:4002
    networks:
      - test

  peer0.orgexporter.adey-meselesh.de:
    container_name: peer0.orgexporter.adey-meselesh.de
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CFG_PATH=/etc/hyperledger/peercfg
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variables
      - CORE_PEER_ID=peer0.orgexporter.adey-meselesh.de
      - CORE_PEER_ADDRESS=peer0.orgexporter.adey-meselesh.de:4003
      - CORE_PEER_LISTENADDRESS=0.0.0.0:4003
      - CORE_PEER_CHAINCODEADDRESS=peer0.orgexporter.adey-meselesh.de:4004
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:4004
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.orgexporter.adey-meselesh.de:4003
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.orgexporter.adey-meselesh.de:4003
      - CORE_PEER_LOCALMSPID=OrgexporterMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_OPERATIONS_LISTENADDRESS=peer0.orgexporter.adey-meselesh.de:4005
      - CORE_METRICS_PROVIDER=prometheus
      - CHAINCODE_AS_A_SERVICE_BUILDER_CONFIG={"peername":"peer0orgexporter"}
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
    volumes:
      - ../organizations/peerOrganizations/orgexporter.adey-meselesh.de/peers/peer0.orgexporter.adey-meselesh.de:/etc/hyperledger/fabric
      - peer0.orgexporter.adey-meselesh.de:/var/hyperledger/production
    working_dir: /root
    command: peer node start
    ports:
      - 4003:4003
      - 4005:4005
    networks:
      - test

  peer0.orgyccu.adey-meselesh.de:
    container_name: peer0.orgyccu.adey-meselesh.de
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CFG_PATH=/etc/hyperledger/peercfg
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variables
      - CORE_PEER_ID=peer0.orgyccu.adey-meselesh.de
      - CORE_PEER_ADDRESS=peer0.orgyccu.adey-meselesh.de:4006
      - CORE_PEER_LISTENADDRESS=0.0.0.0:4006
      - CORE_PEER_CHAINCODEADDRESS=peer0.orgyccu.adey-meselesh.de:4007
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:4007
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.orgyccu.adey-meselesh.de:4006
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.orgyccu.adey-meselesh.de:4006
      - CORE_PEER_LOCALMSPID=OrgyccuMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_OPERATIONS_LISTENADDRESS=peer0.orgyccu.adey-meselesh.de:4008
      - CORE_METRICS_PROVIDER=prometheus
      - CHAINCODE_AS_A_SERVICE_BUILDER_CONFIG={"peername":"peer0orgyccu"}
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
    volumes:
      - ../organizations/peerOrganizations/orgyccu.adey-meselesh.de/peers/peer0.orgyccu.adey-meselesh.de:/etc/hyperledger/fabric
      - peer0.orgyccu.adey-meselesh.de:/var/hyperledger/production
    working_dir: /root
    command: peer node start
    ports:
      - 4006:4006
      - 4008:4008
    networks:
      - test

  peer0.orgethiocta.adey-meselesh.de:
    container_name: peer0.orgethiocta.adey-meselesh.de
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CFG_PATH=/etc/hyperledger/peercfg
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variables
      - CORE_PEER_ID=peer0.orgethiocta.adey-meselesh.de
      - CORE_PEER_ADDRESS=peer0.orgethiocta.adey-meselesh.de:4009
      - CORE_PEER_LISTENADDRESS=0.0.0.0:4009
      - CORE_PEER_CHAINCODEADDRESS=peer0.orgethiocta.adey-meselesh.de:4010
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:4010
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.orgethiocta.adey-meselesh.de:4009
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.orgethiocta.adey-meselesh.de:4009
      - CORE_PEER_LOCALMSPID=OrgethioctaMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_OPERATIONS_LISTENADDRESS=peer0.orgethiocta.adey-meselesh.de:4011
      - CORE_METRICS_PROVIDER=prometheus
      - CHAINCODE_AS_A_SERVICE_BUILDER_CONFIG={"peername":"peer0orgethiocta"}
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
    volumes:
      - ../organizations/peerOrganizations/orgethiocta.adey-meselesh.de/peers/peer0.orgethiocta.adey-meselesh.de:/etc/hyperledger/fabric
      - peer0.orgethiocta.adey-meselesh.de:/var/hyperledger/production
    working_dir: /root
    command: peer node start
    ports:
      - 4009:4009
      - 4011:4011
    networks:
      - test

  peer0.orgsupplier.adey-meselesh.de:
    container_name: peer0.orgsupplier.adey-meselesh.de
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CFG_PATH=/etc/hyperledger/peercfg
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variables
      - CORE_PEER_ID=peer0.orgsupplier.adey-meselesh.de
      - CORE_PEER_ADDRESS=peer0.orgsupplier.adey-meselesh.de:4012
      - CORE_PEER_LISTENADDRESS=0.0.0.0:4012
      - CORE_PEER_CHAINCODEADDRESS=peer0.orgsupplier.adey-meselesh.de:4013
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:4013
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.orgsupplier.adey-meselesh.de:4012
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.orgsupplier.adey-meselesh.de:4012
      - CORE_PEER_LOCALMSPID=OrgsupplierMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_OPERATIONS_LISTENADDRESS=peer0.orgsupplier.adey-meselesh.de:4014
      - CORE_METRICS_PROVIDER=prometheus
      - CHAINCODE_AS_A_SERVICE_BUILDER_CONFIG={"peername":"peer0orgsupplier"}
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
    volumes:
      - ../organizations/peerOrganizations/orgsupplier.adey-meselesh.de/peers/peer0.orgsupplier.adey-meselesh.de:/etc/hyperledger/fabric
      - peer0.orgsupplier.adey-meselesh.de:/var/hyperledger/production
    working_dir: /root
    command: peer node start
    ports:
      - 4012:4012
      - 4014:4014
    networks:
      - test

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:latest
    labels:
      service: hyperledger-fabric
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - FABRIC_LOGGING_SPEC=INFO
      - FABRIC_CFG_PATH=/etc/hyperledger/peercfg
      #- FABRIC_LOGGING_SPEC=DEBUG
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
      - ../organizations:/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations
      - ../scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
    depends_on:
      - peer0.orgexporter.adey-meselesh.de
      - peer0.orgyccu.adey-meselesh.de
      - peer0.orgethiocta.adey-meselesh.de
      - peer0.orgsupplier.adey-meselesh.de
    networks:
      - test
