version: '3.9'

services:
  mongo_db:
    container_name: mongo_db_container
    image: mongo:latest
    restart: always
    ports:
      - 2717:27017
    volumes:
      - mongo_db:/data/db

volumes:
  mongo_db:
    driver: local
